language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-2
matrix:
  include:
    - rvm: 2.6
      env: RUBYOPT=--jit
    - rvm: ruby-head
      env: RUBYOPT=--jit
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
bundler_args: --without local_development
